# Generated by Django 5.2.13 on 2026-04-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_enrollment_unique_together_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
